{{ if index .Values "postgres-database" "enabled" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-homeserver.fullname" . }}-pgbackrest-async
  labels:
    {{- include "matrix-homeserver.labels" . | nindent 4 }}
data:
  {{ with (index .Values "postgres-database" "asyncWalHandling") }}
  async.conf: |
    [global:archive-get]
    process-max = {{ .workersGet }}

    [global:archive-push]
    process-max = {{ .workersPush }}
  {{ end }}
{{- end }}
